name: dhcp
channels:
  - pytorch
  - conda-forge
dependencies:
  - nibabel==5.0.1
  - pip 
  - python
  - pytorch==1.13.1
  - scipy==1.10.1
  - torchaudio==0.13.1
  - torchvision==0.14.1
  - pip:
    - antspyx==0.3.8

